export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const REGISTER_SUCCESS='REGISTER_SUCCESS';
export const REGISTER_FAIL='REGISTER_FAIL';
export const USER_LOADED='USER_LOADED';
export const AUTH_ERROR='AUTH_ERROR';
export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGIN_FAIL='LOGIN_FAIL';

export const GET_PROFILE='GET_PROFILE';
export const GET_PROFILES='GET_PROFILES';
export const GET_REPOS='GET_REPOS';

export const UPDATE_PROFILE='UPDATE_PROFILE';
export const CLEAR_PROFILE='CLEAR_PROFILE';
export const PROFILE_ERROR='PROFILE_ERROR';
export const ACCOUNT_DELETED='ACCOUNT_DELETED';

export const GET_POSTS='GET_POSTS';
export const GET_POST='GET_POST';
export const POST_ERROR='POST_ERROR';
export const UPDATE_LIKES='UPDATE_LIKES';
export const DELETE_POST='DELETE_POST';
export const ADD_POST='ADD_POST';
export const ADD_COMMENT='ADD_COMMENT';
export const REMOVE_COMMENT='REMOVE_COMMENT';

export const GET_COLLECTIONS='GET_COLLECTIONS';
export const GET_COLLECTION='GET_COLLECTION';
export const ADD_COLLECTION='ADD_COLLECTION';
export const UPDATE_COLLECTION='EDIT_COLLECTION';
export const COMPLETE_COLLECTION='COMPLETE_COLLECTION';
export const DELETE_COLLECTION='DELETE_COLLECTION';
export const COLLECTION_ERROR='COLLECTION_ERROR';

export const GET_APPETIZERS='GET_APPETIZERS';
export const GET_APPETIZER='GET_APPETIZER';
export const DELETE_APPETIZER='DELETE_APPETIZER';
export const APPETIZER_ERROR='APPETIZER_ERROR';

export const GET_MAINCOURSES='GET_MAINCOURSES';
export const GET_MAINCOURSE='GET_MAINCOURSE';
export const DELETE_MAINCOURSE='DELETE_MAINCOURSE';
export const MAINCOURSE_ERROR='MAINCOURSE_ERROR';

export const GET_DESSERTS='GET_DESSERTS';
export const GET_DESSERT='GET_DESSERT';
export const DELETE_DESSERT='DELETE_DESSERT';
export const DESSERT_ERROR='DESSERT_ERROR';

export const GET_MENUS='GET_MENUS';
export const GET_MENU='GET_MENU';
export const MENU_ERROR='MENU_ERROR';
export const DELETE_MENU='DELETE_MENU';
export const ADD_MENU='ADD_MENU';
export const EDIT_MENU='EDIT_MENU';
export const REMOVE_MENU='REMOVE_MENU';

export const GET_TRANSACTIONS='GET_TRANSACTIONS';
export const GET_TRANSACTION='GET_TRANSACTION';
export const TRANSACTION_ERROR='TRANSACTION_ERROR';

export const GET_ITEMS='GET_ITEMS';
export const GET_ITEM='GET_ITEM';
export const ITEM_ERROR='ITEM_ERROR';